### ISSUE TITLE
config() returns an empty {}

### ISSUE THREAD

**Issue by shinokada** [pietvanzoen/deno-dotenv#22]
Following this doc.

In .env

```
GREETING = Hello Deno
PORT = 8777
...
```

In app.ts

```
import { config } from "https://deno.land/x/dotenv/mod.ts";
console.log(config());
```

When I run:

```
$ cat .env
GREETING = Hello Deno
PORT = 8777
...
$ deno run --allow-read --allow-env app.ts
{}
```

What am I missing or doing wrong here?

**Comment by pietvanzoen** [comment]
Remove the spaces around the `=` and it will work. But I'll look into supporting what you have here.

**Comment by shinokada** [comment]
Thanks. 
It happens automatically when I save a file on the VS code.

**Comment by shinokada** [comment]
It works without spaces. It requires `--allow-read` flag. 

I thought only `--allow-env` is  required.

```
deno run --allow-read app.ts
{ GREETING: "Hello Deno", PORTk: "8777" }
```

**Comment by pietvanzoen** [comment]
Ah! Yes. The docs need updating there. Updated here: #23 

Also adding support for spaces around the `=`. 

Do you mean VSCode added the spaces around the `=`?

**Comment by shinokada** [comment]
Yes, VS Code adds the spaces around `=`.
Thanks. 
Can you merge it with the master?

**Comment by pietvanzoen** [comment]
Merged!

**Comment by shinokada** [comment]
Thanks. It works.

**Comment by pietvanzoen** [comment]
excellent!
