### ISSUE TITLE
numbers inside variables

### ISSUE THREAD

**Issue by danielbeeke** [pietvanzoen/deno-dotenv#26]
Hi 

I have some variables that have numbers in them. Like ABC1 or XYZ2.
They don't seem to work.

https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

Here it looks like it should be possible.

**Comment by pietvanzoen** [comment]
Thanks @danielbeeke! I've updated and merged with this PR #27.

Released with v0.4.2.

**Comment by danielbeeke** [comment]
Thank you Piet! Works like a charm
