### ISSUE TITLE
Feature Request: JSON to Object

### ISSUE THREAD

**Issue by zinthose** [pietvanzoen/deno-dotenv#33]
I'm going to tinker with support to directly import JSON as an object to the returned config object.
`Headers={Accept:="application/json", "Content-Type": "application/json;charset=UTF-8"}`
would become:
```javascript
console.log(config["Headers"])
{
  Accept: "application/json",
  "Content-Type": "application/json;charset=UTF-8"
}
```

I'll send a pull request when I'm happy with it.

**Comment by zinthose** [comment]
I have an update on my fork [import-json2object](https://github.com/zinthose/deno-dotenv/tree/import-json2object) branch that allows for automatic parsing of JSON strings into objects.  This is a code breaking change thus why I have not submitted a pull request.

**Comment by pietvanzoen** [comment]
Apologies for my lack of response to this. I was on vacation and I'm catching up now.

I wonder if a better and more general approach would be good here. Such as allowing users pass a parsing function. This would allow features like the one you suggested but also allow any other parsing a user might like. E.g:

```js
const conf = config({ 
  parseValue: (value, key) => { 
    try {
      return JSON.parse(value);
    } catch(e) {
      return value;
    }
  }
});
```

Would you find this useful for your use case? 

One difficulty with building the parsing into the library as you suggest is the inconsistent behaviour of returned values from `Deno.env.get('FOO')` vs `conf.FOO`. Assuming `FOO` is a JSON string in the `.env` file. `Deno.env.set('FOO', value)` requires a string to be set for the value.

**Comment by zinthose** [comment]
No worries, I've been busy all week myself.  I closed my pull request in part to the issue you brought up.  I'm spending time with the family atm but will return to this soon.

**Comment by pietvanzoen** [comment]
Doing some housekeeping and closing this as a stale issue. Feel free to post any updates.
