### ISSUE TITLE
Parsing numbers, booleans and null values

### ISSUE THREAD

**Issue by wjstraver** [pietvanzoen/deno-dotenv#36]
Hi,

First off, I like how easy it is with this package to import .env values into my project. However, I've noticed in my test projects, I'll would like it if true/false are parsed as boolean, numbers are correctly parsed, empty values are null or undefined instead of an empty string.

Right now I add the following code to my projects:

```ts
import {config} from "https://deno.land/x/dotenv@v0.5.0/mod.ts";

type EnvValue = null|number|boolean|string

type EnvObject = {
    [key: string]: EnvValue
}

export const env = Object.entries(config())
    .reduce((envObj: EnvObject, [key, value]: [string, string]) => {
        if(value === "" || value === "null") {
            envObj[key] = null;
        } else if (/^true|false$/i.test(value)) {
            envObj[key] = JSON.parse(value.toLowerCase());
        } else if (/^(\d*\.?\d+)$/.test(value)) {
            envObj[key] = parseFloat(value);
        } else {
            envObj[key] = value;
        }

        return envObj;
    }, {});
```

How would you look at the idea of implementing this something along the line of:

```ts
config({parseTypes: true});
```

**Comment by wjstraver** [comment]
Hi,

I understand why you would like to stay true to the environment variables by keeping everyting as strings. I'll take a look in creating a helper module myself. Maybe adding something like `getEnv('ENV_NAME', 'default value')` or other small features as well.

Will let you know when/if I have something!

**Comment by pietvanzoen** [comment]
Doing some housekeeping and closing this issue. Feel free to comment if you have any updates.

Cheers
