### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [pietvanzoen/deno-dotenv#38]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

Ask me anything if you have some problem.

**Comment by pietvanzoen** [comment]
Hi there! Thanks for the suggestion. Currently I don't think the project is big enough to warrant it's own website. But I'll keep it in mind for the future. Thanks!
