### ISSUE TITLE
Clarify env order preference

### ISSUE THREAD

**Issue by webdeb** [pietvanzoen/deno-dotenv#39]
I am facing an issue where the ENV variable I am passing via the CLI is ignored in favour of `.env`

```
.env
MODE=dev
```

```
MODE=prod deno run --allow-read --allow-env main.ts
```

```
// main.ts
import 'https://deno.land/x/dotenv@v0.5.0/load.ts';
const mode = Deno.env.get('MODE')

console.log(mode) // dev
```

**Comment by webdeb** [comment]
In nodes dotenv package existing environment variables get not overridden 
https://github.com/motdotla/dotenv/blob/master/lib/main.js#L99

I would suggest to put a `if (Deno.env.get(key) === undefined)` before calling `Deno.env.set(key, conf[key])` in https://github.com/pietvanzoen/deno-dotenv/blob/5de687748d2d3d00e83569fd5bfcabdd2f4c60d0/mod.ts#L60

**Comment by pietvanzoen** [comment]
Thanks for posting this issue @webdeb! This was very much the intended behaviour but overlooked. 

I've fixed and released as a major release since some folks may be relying on the old behaviour.

**Comment by webdeb** [comment]
@pietvanzoen 🎉

**Comment by webdeb** [comment]
@pietvanzoen do you know when v1.0.0 will be available on deno.land ? I was thinking that deno.land will automatically proxy to the repo and cache the new version, but its still 404. Do you have any ideas about this?
https://deno.land/x/dotenv@v1.0.0

**Comment by pietvanzoen** [comment]
Apologies @webdeb. It's released now on Deno.land as v1.0.1: https://deno.land/x/dotenv@v1.0.1

**Comment by webdeb** [comment]
@pietvanzoen awesome, thank you!
