### ISSUE TITLE
Cannot import the dependency.

### ISSUE THREAD

**Issue by Ayfri** [pietvanzoen/deno-dotenv#41]
Hi, I'm using Deno 1.5.1 and when I try to import the dependency I'm getting every time this error : 
```typescript
warning: Compiled module not found "https://deno.land/x/dotenv/mod.ts"
  From: file:///C:/Users/Pierre/WebstormProjects/deno/tsc-bot/deps.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/dotenv/mod.ts' does not provide an export named 'config'
```

This is the code : `import { config } from "https://deno.land/x/dotenv/mod.ts";`

**Comment by pietvanzoen** [comment]
Thanks for the issue @Ayfri ! Reading the Deno discord it sounds like there are some caching issues with 1.5.1. Can you try running `deno cache` on the file where you're importing `dotenv` and running again? 

I'm not 100% sure why but this seems to fix some things. Let me know.

**Comment by Ayfri** [comment]
It worked thanks!
Strange issue...

**Comment by pietvanzoen** [comment]
Very! Glad it worked!

**Comment by stolinski** [comment]
I'm also hitting this as a new user and `deno cache filename.ts` did fix. I'm wondering if this is something that can be prevented from happening. I'm pretty new to Deno, but would be happy to attempt to help.
