### ISSUE TITLE
Support updating .env file

### ISSUE THREAD

**Issue by jsejcksn** [pietvanzoen/deno-dotenv#42]
This is a request for a new module export for updating a `.env` file with a new key/value pair.

It would overwrite an existing entry with a matching key or add a new entry if one does not already exist.

Here's an example which uses the name `update` (although I'm not necessarily prescribing that name):

`.env`:
```
LOCATION=world
```

`script.ts`:
```ts
import {update} from 'https://deno.land/x/dotenv/mod.ts';

update('LOCATION', 'Earth');
update('GREETING', 'Hello');
```

```
> cat .env
LOCATION=world

> deno run script.ts

> cat .env
LOCATION=Earth
GREETING=Hello
```

There are obviously other considerations involved which are not shown in the example (e.g. configuring path to `.env` file), and even more considerations which would be implementation details (preserving unparsed data like comments in the file during overwrite, escaping certain strings, etc.). This comment is just to communicate the concept.

**Comment by pietvanzoen** [comment]
Could you describe the use case for such a feature? 

It is possible to update environment variables in your running application via `Deno.env.set`.

**Comment by jsejcksn** [comment]
> Could you describe the use case for such a feature?

@pietvanzoen To allow using `.env` as a persistent key-value store

**Comment by pietvanzoen** [comment]
Gotcha. I can see the value of such a feature in certain situations. But it's a bit beyond the scope of this module as I see it.

If you happen to find/develop something that does this I'd be happy to point to it in the readme.

**Comment by jsejcksn** [comment]
> If you happen to find/develop something that does this I'd be happy to point to it in the readme.

@pietvanzoen Sounds good. If I do, I'll follow up.
