### ISSUE TITLE
Modify parser's whitespace handling

### ISSUE THREAD

**Issue by jsejcksn** [pietvanzoen/deno-dotenv#43]
Hello. I have found a bug with the current parser. Here is an example:

```
% cat .env
# tests
LF_BARE=hello\nworld
LF_DQ="hello\nworld"
LF_SQ='hello\nworld'

CRLF_BARE=hello\r\nworld
CRLF_DQ="hello\r\nworld"
CRLF_SQ='hello\r\nworld'

TRIM_BARE= hello world 
TRIM_DQ=" hello world "
TRIM_DQ2= " hello world " 
TRIM_SQ=' hello world '
TRIM_SQ2= ' hello world ' 

% cat example.ts
import {config} from 'https://deno.land/x/dotenv@v1.0.1/mod.ts';
console.log(config());

% deno run --allow-read=.env example.ts
{
  LF_BARE: "hello\\nworld",
  LF_DQ: "hello\nworld",
  LF_SQ: "hello\\nworld",
  CRLF_BARE: "hello\\r\\nworld",
  CRLF_DQ: "hello\\r\nworld",
  CRLF_SQ: "hello\\r\\nworld",
  TRIM_BARE: "hello world",
  TRIM_DQ: "hello world",
  TRIM_DQ2: "hello world",
  TRIM_SQ: "hello world",
  TRIM_SQ2: "hello world"
}

```

For all of the keys which begin with `TRIM_` (except for `TRIM_BARE`), the results are not what is expected.

If a value is not quoted, then I understand that trimming leading and trailing whitespace is desirable, but for quoted values, this should not be the case, since it makes it impossible to define values including whitespace at the ends.

I think this module is based on the Node `dotev` module, right? Here is a reference to its [parsing rules](https://github.com/motdotla/dotenv/blob/7301ac9be0b2c766f865bbe24280bf82586d25aa/README.md#rules):

> ### Rules
> 
> The parsing engine currently supports the following rules:
> 
> - `BASIC=basic` becomes `{BASIC: 'basic'}`
> - empty lines are skipped
> - lines beginning with `#` are treated as comments
> - empty values become empty strings (`EMPTY=` becomes `{EMPTY: ''}`)
> - inner quotes are maintained (think JSON) (`JSON={"foo": "bar"}` becomes `{JSON:"{\"foo\": \"bar\"}"`)
> - whitespace is removed from both ends of unquoted values (see more on [`trim`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)) (`FOO=  some value  ` becomes `{FOO: 'some value'}`)
> - single and double quoted values are escaped (`SINGLE_QUOTE='quoted'` becomes `{SINGLE_QUOTE: "quoted"}`)
> - single and double quoted values maintain whitespace from both ends (`FOO="  some value  "` becomes `{FOO: '  some value  '}`)
> - double quoted values expand new lines (`MULTILINE="new\nline"` becomes
> 
> ```
> {MULTILINE: 'new
> line'}
> ```

Also, I'm not sure how the original Node module handles CRLFs in quoted values, but (as you can see in the example) this module does not convert double-quoted CRLF (`\\r\\n`) to `\r\n` — only the LFs. Perhaps this can be changed as well.

**Comment by jsejcksn** [comment]
> Also, I'm not sure how the original Node module handles CRLFs in quoted values, but (as you can see in the example) this module does not convert double-quoted CRLF (`\\r\\n`) to `\r\n` — only the LFs. Perhaps this can be changed as well.

It appears that the Node module does not transform CRLF:

https://github.com/motdotla/dotenv/blob/7301ac9be0b2c766f865bbe24280bf82586d25aa/lib/main.js#L54-L65

**Comment by pietvanzoen** [comment]
Hello! Apologies for the delay in responding to this. I haven’t been able to look into this but hope to this week. 

In the mean time PRs are welcome. :)

**Comment by jsejcksn** [comment]
> Hello! Apologies for the delay in responding to this. I haven’t been able to look into this but hope to this week.
> 
> In the mean time PRs are welcome. :)

Hello, Piet. No apologies necessary! If I beat you to it, I'll send a PR.
