### ISSUE TITLE
deno compile not working

### ISSUE THREAD

**Issue by proflylab** [pietvanzoen/deno-dotenv#44]
i'm getting "undefined"
on deno 1.6.1
![image](https://user-images.githubusercontent.com/27909158/102388468-5c72b400-4004-11eb-8220-f83d97dcd65c.png)

**Comment by pietvanzoen** [comment]
Hi @proflylab. Thanks for the message. Could you give me the list of commands and any relevant files you're running so I can accurately replicate the behaviour you're seeing please?

**Comment by proflylab** [comment]
> 
> 
> Hi @proflylab. Thanks for the message. Could you give me the list of commands and any relevant files you're running so I can accurately replicate the behaviour you're seeing please?

my code

```
# .env
GREETING=hello world
```
```
import "https://deno.land/x/dotenv/load.ts";

console.log(Deno.env.get('GREETING'));
```

test on 
deno 1.6.1  
dot-env 2.0.0

this command line is working
```
deno run --allow-env --allow-read .\app.ts 
```

this not working
```
deno compile --unstable .\app.ts
```

**Comment by proflylab** [comment]
> 
> 
> > Hi @proflylab. Thanks for the message. Could you give me the list of commands and any relevant files you're running so I can accurately replicate the behaviour you're seeing please?
> 
> my code
> 
> ```
> # .env
> GREETING=hello world
> ```
> 
> ```
> import "https://deno.land/x/dotenv/load.ts";
> 
> console.log(Deno.env.get('GREETING'));
> ```
> 
> test on
> deno 1.6.1
> dot-env 2.0.0
> 
> this command line is working
> 
> ```
> deno run --allow-env --allow-read .\app.ts 
> ```
> 
> this not working
> 
> ```
> deno compile --unstable .\app.ts
> ```

![image](https://user-images.githubusercontent.com/27909158/102719402-7ff96f80-4320-11eb-8043-c79581e849d1.png)

**Comment by proflylab** [comment]
> 
> 
> > > Hi @proflylab. Thanks for the message. Could you give me the list of commands and any relevant files you're running so I can accurately replicate the behaviour you're seeing please?
> > 
> > 
> > my code
> > ```
> > # .env
> > GREETING=hello world
> > ```
> > 
> > 
> > ```
> > import "https://deno.land/x/dotenv/load.ts";
> > 
> > console.log(Deno.env.get('GREETING'));
> > ```
> > 
> > 
> > test on
> > deno 1.6.1
> > dot-env 2.0.0
> > this command line is working
> > ```
> > deno run --allow-env --allow-read .\app.ts 
> > ```
> > 
> > 
> > this not working
> > ```
> > deno compile --unstable .\app.ts
> > ```
> 
> ![image](https://user-images.githubusercontent.com/27909158/102719402-7ff96f80-4320-11eb-8043-c79581e849d1.png)

but it work
```
import { config } from "https://deno.land/x/dotenv/mod.ts";
```

**Comment by proflylab** [comment]
> 
> 
> Hi @proflylab. Thanks for the message. Could you give me the list of commands and any relevant files you're running so I can accurately replicate the behaviour you're seeing please?

my code

```
# .env
GREETING=hello world
```

```
import "https://deno.land/x/dotenv/load.ts";

console.log(Deno.env.get('GREETING'));
```

test on
deno 1.6.1
dot-env 2.0.0

this command line is working

```
deno run --allow-env --allow-read .\app.ts 
```

this not working

```
deno compile --unstable .\app.ts
```

![image](https://user-images.githubusercontent.com/27909158/102719803-cd76dc00-4322-11eb-80f4-b43502d1f9c5.png)

**Comment by pasha-bolokhov** [comment]
When you do `deno compile`, you still need to provide the same permissions `--allow-env --allow-read` that you used when you were doing `deno run`.
This is not an issue of this package — you can check this yourself.
If you agree, you can close this issue (or so can @pietvanzoen)

**Comment by proflylab** [comment]
> When you do `deno compile`, you still need to provide the same permissions `--allow-env --allow-read` that you used when you were doing `deno run`. This is not an issue of this package — you can check this yourself. If you agree, you can close this issue (or so can @pietvanzoen)

thank you, deno lasted version it work but deno 1.6.1 not work
