### ISSUE TITLE
dotenv does not load variables to Deno.env

### ISSUE THREAD

**Issue by tymfear** [pietvanzoen/deno-dotenv#50]
deno --version output
```
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

.env file
```
# .env
HELLOWORLD=hello world
```

testenv.ts
```typescript
import { config } from "https://deno.land/x/dotenv@v2.0.0/mod.ts";

console.log(Deno.env.get("HELLOWORLD"));
console.log(config());
```

output of `deno run -A testenv.ts`
```
undefined
{ HELLOWORLD: "hello world" }
```
Though it loads it to the `config` method output

**Comment by pietvanzoen** [comment]
`config` doesn’t export to to `Deno.env` by default. But you can pass a flag to enable that. Also be sure to call config before trying to access the variable via `Deno.env`. 

```ts

import { config } from "https://deno.land/x/dotenv@v2.0.0/mod.ts";

console.log(config({ export: true }));
console.log(Deno.env.get("HELLOWORLD"));

```

alternatively you can auto load the variables into Deno.env: https://github.com/pietvanzoen/deno-dotenv#auto-loading

```ts
// app.ts
import "https://deno.land/x/dotenv/load.ts";

console.log(Deno.env.get("GREETING"));
```

I hope this helps. Let me know how you get on. :)

**Comment by tymfear** [comment]
@pietvanzoen , that helped, thanks! Haven't seen the difference in import URL for `load` and `config`.
